services:
  postgres:
    image: postgres:16
    container_name: admin-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: adminservice
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scrooge-net

  admin-service:
    build: .
    container_name: admin-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/adminservice
    ports:
      - '8080:8080'
    networks:
      - scrooge-net

volumes:
  pgdata: {}

networks:
  scrooge-net:
    driver: bridge
